#  GET http://localhost:3000/api/user/2

POST http://localhost:3000/api/user/register
Content-Type: application/json

 {
        "firstName": "Faizan",
        "lastName": "Mukhtar",
        "instituteID" : 1,
        "levelID" : 1,
        "gender": "Male",
        "emailID": "faizan@gmail.com",
        "password": "iloveallah",
        "profileImageUrl": "errrrrrrrr",
        "dateJoined": "2022-12-12"
    }